name: Sportify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  intl: ^0.20.2
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  image_picker: ^1.0.7
  path: ^1.8.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Letakkan di bagian paling bawah file
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
